### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by coolpalani** [pradiptapks/RedHat_OpenStack_12_Director#1]
Hi,

Can I have instructions for deploy RedHat OpenStack 12 with single NIC using your repo
I am not seeing any instructions for deploy undercloud

**Comment by pradiptapks** [comment]
Hi,
Please refer RedHat official documentation for Director deployment and customise the template with single nic.
https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/?version=12 https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/12/html-single/director_installation_and_usage/

For any technical issue please raise a case against to redhat with the valid subscription. https://access.redhat.com/support/cases/
